examples/peps.jl
examples/tensor_network_tools/tensor_network_tools.jl
src/tensor_networks.jl
test/runtests.jl

Add approximate PEPS inner product contraction by inserting projectors determined from a boundary MPS-MPO contraction.

Add approximate PEPS inner product contraction

---

Project.toml
README.md
examples/README.jl
examples/TTN/ttn_type.jl
examples/contraction_sequence/contraction_sequence.jl
examples/mps.jl
examples/peps/ising_tebd.jl
src/ITensorNetworks.jl
src/abstractitensornetwork.jl
src/apply.jl
src/contraction_sequences.jl
src/expect.jl
src/exports.jl
src/imports.jl
src/namedgraphs.jl
src/requires/omeinsumcontractionorders.jl
src/requires/omeinsumcontractionorders_itensorcontractiontree.jl
src/tebd.jl
test/runtests.jl
test/test_contraction_sequence.jl
test/test_tebd.jl

This adds a variety of more efficient but potentially sub-optimal contraction sequence algorithms from [OMEinsumContractionOrders.jl](https://github.com/TensorBFS/OMEinsumContractionOrders.jl), based on the wrapper @GiggleLiu wrote in [ITensorContractionOrders.jl](https://github.yanqishui.work/GiggleLiu/ITensorContractionOrders.jl).
It is based around a single function `contraction_sequence(tn::ITensorNetwork; alg="optimal")` where `alg="optimal"` chooses the optimal but exponentially scaling algorithm implemented in `ITensors.jl` (in the submodule `ITensors.ContractionSequenceOptimization`), and this PR provides the alternative backends `"greedy"`, `"tree_sa"`, `"sa_bipartite"`, and `"kahypar_bipartite"` when `OMEinsumContractionOrders.jl` is loaded with `using …

Contraction sequence backends

---

src/treetensornetworks/abstracttreetensornetwork.jl
src/treetensornetworks/solvers/contract.jl
test/test_treetensornetworks/test_solvers/test_contract.jl

Fixes tests for `contract(::AbstractTTN, ::AbstractTTN)` by fixing a bug in `inner(::AbstractTTN, ::AbstractTTN)` and changing the initial states used in the tests. Aside from the bug making it it seem like the algorithm failed when it actually didn't, the updated behavior for the initial state always starts from a product state by default. So the `nsite=2` case needs more sweeps to be able to grow the bond dimension enough, and the `nsite=1` case couldn't work without explicitly supplying an initial state with a nontrivial bond dimension.

Fix `contract` tests

---

src/binary_tree_partition.jl
src/exports.jl
src/mincut.jl
test/test_binary_tree_partition.jl

Introduce APIs below as is discussed in https://github.com/mtfishman/ITensorNetworks.jl/pull/66:
```julia
"""
Outputs a maximimally unbalanced directed binary tree DataGraph defining the desired graph structure
"""
function path_graph_structure(tn::ITensorNetwork)
end
"""
Outputs a directed binary tree DataGraph defining the desired graph structure
"""
function binary_tree_structure(tn::ITensorNetwork)
end
function partition(
::Algorithm"mincut_recursive_bisection", tn::ITensorNetwork, inds_btree::DataGraph
)
function partition(tn::ITensorNetwork, inds_btree::DataGraph; alg::String)
return partition(Algorithm(alg), tn, inds_btree)
end
```

Introduce `binary_tree_structure`, `path_graph_structure`, and rename `binary_tree_partition`

---

src/specialitensornetworks.jl

Added Functions to `specialitensornetworks.jl` for creating the Tensor Network State corresponding to the square root of the classical ising partition function.
Also:
i) Removed a repeated docstring.
ii) Specified the link_space argument in `ising_network` so it works for both an index network with siteinds and without.

Square root ising

---

src/binary_tree_partition.jl
test/test_binary_tree_partition.jl

This PR makes binary tree partition work when the input tn is disconnected. Example:
```julia
inds = [Index(2, "$i") for i in 1:5]
tn = ITensorNetwork([randomITensor(i) for i in inds])
par = partition(tn, binary_tree_structure(tn); alg="mincut_recursive_bisection")
```
For this case, we still want `par` to be connected so that it has a binary tree structure. To achieve that, we add multiple scalar tensors with value 1.0 to maintain connectivity, without changing the output value.

Let binary tree partition support the disconnected tensor network

---

src/contraction_tree_to_graph.jl
test/test_contraction_sequence_to_graph.jl

Given a contraction sequence, the output of  `contraction_sequence_to_graph` gives the partition information of the contraction sequence. However, multiple important information such as the contraction order, as well as the root of the contraction sequence, is lost. The output of `contraction_sequence_to_digraph` is a directed graph that keeps such informations.
Example: when the input sequence is [[1,2], [3,4]], the output of the `contraction_sequence_to_digraph` will be a graph with the structure of 
```
[1,2,3,4]
/    \
[1,2]  [3,4]
/  \    /  \
1    2   3   4
```
while the output of `contraction_sequence_to_graph` will be an undirected graph with the structure of 
```
[1,2]----[3,4]
/  \    /  \
1    2   3   4
```

Introduce `contraction_sequence_to_digraph` and simplify `contraction_sequence_to_graph`

---

src/treetensornetworks/opsum_to_ttn.jl
test/test_opsum_to_ttno.jl

In the spirit of better late than never, a fix for #62. I still need to figure out the problem with the manual svd compression so we can default to that and remove the current redundancy, but this might take some time so I just patched the current working version for now.
The issue was that the finite state machine representation just overwrote the on-site entry every time an on-site term was added; I just didn't think of on-site sums writing it. Wrapping everything in a `Sum{...}` fixes it. I added a small test.

Fix `OpSum` to `TTN` converter for multiple on-site operators

---

src/indextags.jl
src/sitetype.jl

Quick PR to improve Edge tag naming and allow for longer tag names.
Should resolve Issue #78

Better Edge Tag Naming

---

src/treetensornetworks/opsum_to_ttn.jl
test/test_opsum_to_ttn.jl

Fixes the manual compression in the `OpSum` to `TTN` converter. I switched the default `OpSum` to `TTN` converter to always use the compression now. As far as I can tell this now works for any combination of interactions (I extended the corresponding tests a bit), and always gives the correct compressed bond dimension.
I left the explicit finite state machine construction for now since this might be useful for debugging purposes, but it's no longer exported. Maybe this might be useful if we ever want to use a fully sparse Hamiltonian representation instead of always making a dense operator, but I can also remove it if you think that's better.

Fix channel compression in `OpSum` to `TTN` converter

---

src/itensornetwork.jl
test/test_itensornetwork.jl

For example:
```julia
i, j, k, l = Index.(fill(2, 4))
A = ITensor(i, j)
B = ITensor(j, k)
C = ITensor(k, l)
tn = ITensorNetwork(["A", "B", "C"], [A, B, C])
tn = ITensorNetwork(["A" => A, "B" => B, "C" => C])
```

Add more general ITensorNetwork constructors from collections of ITensors

---

examples/dynamics/heavy_hex_ising_real_tebd.jl
src/beliefpropagation/beliefpropagation.jl
test/test_gauging.jl

Further update to Heavy Hex dynamics example by simplifying the graph construction procedure based on the new features in the PR https://github.com/mtfishman/NamedGraphs.jl/pull/37 in NamedGraphs.jl
Also fixed a few bugs in beliefpropagation.jl which cropped up in testing.

Use simpler constructors for heavy hex lattice

---

src/ITensorNetworks.jl
src/abstractitensornetwork.jl
src/imports.jl
test/test_additensornetworks.jl

This PR adds the capability to add two `itensornetworks` provided they are of the same structure (edges, vertices).
Tests are included.

`add(::ITensorNetwork, ::ITensorNetwork)` with `directsum` backend

---

src/abstractitensornetwork.jl
src/gauging.jl

Recent changes to `ITensor` mean that it is stricter about erroring over unsupported keyword arguments.
This raises errors in the current version of `ITensorNetworks`: especially in the internal `tree_solver` functions.
This PR aims at fixing these errors. I have picked up a few in `abstractitensornetwork.jl` and `gauging.jl` but a lot remain on the `tree_tensornetworks/solvers` and should be addressed.

Resolve keyword argument issues

---

examples/peps.jl

Use `ITensorNetworks.heisenberg` in PEPS example.

Use `ITensorNetworks.heisenberg` in PEPS example

---

src/treetensornetworks/abstracttreetensornetwork.jl
test/test_treetensornetworks/test_expect.jl

This PR addresses #128 and adds an implementation of expect that should allow evaluation of local observables at all sites in a `TTN` at linear cost in the number of vertices in the `TTN`.
Basic tests have been added:
- comparing with `ITensors.expect` evaluated on the output of `random_mps` converted to `ITensors.MPS`, as well as verifying the `Sz`
- expectation value for a product-TTN in the computational basis for a `comb_tree`.
Open issues:
- performance testing should be added at some point / optimality of implementation is not verified
- Currently does not support multiple site-indices per vertex. This could probably easily be addressed similar to the way this is handled in the `svd_ttn` for converting `OpSum` to `TTN`.

Efficient implementation of `expect` for `AbstractTTN`

---

src/itensornetwork.jl
src/models.jl
src/treetensornetworks/projttns/abstractprojttn.jl
src/treetensornetworks/ttn.jl
src/utils.jl
test/test_itensornetwork.jl
test/test_treetensornetworks/test_solvers/test_tdvp.jl

This PR addresses some bugs in `alternating_update` when using certain `vertextype`s.
- Removed `maybe_only` from `utils.jl` and `models.jl` since it is not needed anymore
- Added default `link_space=1` to `random_ttn`, in line with `ITensors.randomMPS`, to avoid disconnecting product tree tebsir networks during first sweep.#140
- Make `alternating_update` compatible with e.g. binary trees. This used to fail due to [loss of type-information](https://github.com/andyferris/Dictionaries.jl/issues/97) of `Dictionaries.getindices` when applied to certain empty `Dictionary`.
- Added test for the latter functionality.
It does not address issues relating to ill-defined `isless` comparison on arbitrary `vertextype` in `ttn_svd`, which should be resolved in a separate PR.

Improve compatibility with arbitrary vertextypes and tree structures 

---

Project.toml
src/treetensornetworks/projttns/projttn.jl
test/test_treetensornetworks/Project.toml
test/test_treetensornetworks/test_position.jl

Fixes https://github.com/TRIQS/tns_solver/issues/12.

Fix `ProjTTN` constructor for mixed input vertex types

---

src/formnetworks/quadraticformnetwork.jl
test/test_forms.jl

This PR fixes a bug in the `QuadraticFormNetwork(ket::AbstractITensorNetwork; kwarg...)` constructor where a `bra` variable was being passed that doesn't exist.
This PR should fix that and adds a quick test for the above constructor so that it would get caught in the future.

Fix bug in QuadraticFormNetwork constructor when no operator present

---

src/abstractitensornetwork.jl
test/test_contraction_sequence_to_graph.jl

PR to remove `flatten_networks(...)` as it is not being used for anything meaningful anymore in the library.
The test where it was being used in `test_contraction_sequence_to_graph` now directly constructs a `flatened` network by just calling `ITensorNetwork(g; link_space =2)` avoiding any use of `siteinds`.
This should address Issue #164

Remove flatten networks and refactor test

---

src/caches/beliefpropagationcache.jl
src/contract.jl
test/test_belief_propagation.jl

This PR fixed the `bp` edge case where the network contracts to the scalar `0` which would previously yield `Nan`.
This is achieved by:
1. Updating the `default_message_update` function to only divide by the `norm` if its not zero -> avoiding the creating of message tensors with `nan` in them.
2. Adding to `logscalar(alg::Algorithm"bp", tn::AbstractITensorNetwork)` a check if any of the denominators terms are zero. If this is the case then `log(tn)` should be `-Inf`. This is because, on a tree, if the product of `message(pe)` and `message(reverse(pe)` on any `partitionedge` is zero then the contraction of the tree must be zero (assuming the messages are converged).
A quick test is added.
@ryanlevy this should fix the issue with `bp` in `ITensorNumericalAnalysis.jl`

Account for BP edge case where network evaluates to 0

---

Project.toml
ext/ITensorNetworksOMEinsumContractionOrdersExt/ITensorNetworksOMEinsumContractionOrdersExt.jl
src/lib/ModelNetworks/src/ModelNetworks.jl
src/mpo_mps_compatibility.jl
test/test_belief_propagation.jl
test/test_binary_tree_partition.jl
test/test_contract_deltas.jl
test/test_forms.jl
test/test_gauging.jl
test/test_itensornetwork.jl
test/test_itensorsextensions.jl
test/test_treetensornetworks/test_solvers/test_contract.jl
test/test_treetensornetworks/test_solvers/test_dmrg.jl
test/test_ttno.jl
test/test_ttns.jl

See https://github.com/ITensor/ITensorMPS.jl/issues/19.

Use `random_itensor`, `random_mps`, etc.

---

Project.toml
ext/ITensorNetworksAdaptExt/ITensorNetworksAdaptExt.jl
test/Project.toml
test/test_ext/Project.toml
test/test_ext/test_itensornetworksadaptext.jl

With this we can now do:
```julia
using Metal: mtl
using NamedGraphs.NamedGraphGenerators: named_grid
using ITensorNetworks: random_tensornetwork, siteinds
g = named_grid((2, 2))
s = siteinds("S=1/2", g)
tn = random_tensornetwork(s)
tn_mtl = mtl(tn)
```
and we can see the tensors have been moved to GPU:
```julia
julia> tn[1, 1]
ITensor ord=3 (dim=2|id=976|"S=1/2,Site,n=1×1") (dim=1|id=434|"1×1,2×1") (dim=1|id=601|"1×1,1×2")
NDTensors.Dense{Float64, Vector{Float64}}
julia> tn_mtl[1, 1]
ITensor ord=3 (dim=2|id=976|"S=1/2,Site,n=1×1") (dim=1|id=434|"1×1,2×1") (dim=1|id=601|"1×1,1×2")
NDTensors.Dense{Float32, Metal.MtlVector{Float32, Metal.MTL.Private}}
```
@JoeyT1994 with this you should then be able to follow the same instructions that are shown here: …

Add support for Adapt which enables converting tensor networks to GPU

---

src/solvers/insert/insert.jl

This PR adds the line `state = copy(state)` at the beginning of the `default_inserter` function. Fixes #189.

copy the state at the beginning of default_inserter

---

src/caches/beliefpropagationcache.jl
test/test_belief_propagation.jl
test/test_gauging.jl

This PR alters the `message_diff` function in BP to do a better convergence test.
Specifically, it defines it as `1 - |<m_{e, t+1}|m_{e, t}>|^{2}` where `|m_{e, t}>` is the message tensor (reshaped as a vector) on edge e at iteration `t`  and `|m_{e, t}>` is the message tensor (reshaped as a vector) on edge e at the subsequent iteration.
It is analogous to the infidelity measure for a quantum wavefunction and a strict lower bound on the trace distance,
i.e. `1 - |<m_{e, t+1}|m_{e, t}>|^{2} <= 0.5*Tr(|m_{e, t}><m_{e, t}| - |m_{e, t+1}><m_{e, t+1}|)`
Importantly, it is independent of a "phase" factor `e^i\theta` difference between the two messages, something which I believe the Euclidean distance isn't and therefore would run into trouble with complex numbers.

Fix BP convergence metric for complex networks

---

Project.toml
src/solvers/local_solvers/exponentiate.jl

This PR fixes a typo in the exponentiate solver where the `eager` flag was intended to be passed, but was not being. In practice I have found that `eager=true` is indeed a good default and makes a big difference to performance.

Pass eager flag to KrylovKit.exponentiate
